apiVersion: v1
kind: Namespace
metadata: 
    name: dev

---

apiVersion: v1 
metadata: 
     name: nginx-pod
     namespace: dev
kind:  Pod
spec: 
     containers:
      - name: nginx-container 
        image: nginx
        ports:
          - containerPort: 80