<<<<<<< HEAD
apiVersion: v1 
metadata: 
     name: nginx-pod
kind:  Pod
spec: 
     containers:
      - name: nginx-container 
        image: nginx
        ports:
          - containerPort: 80
=======
apiVersion: v1 
metadata: 
     name: nginx-pod
kind:  Pod
spec: 
     containers:
      - name: nginx-container 
        image: nginx
        ports:
          - containerPort: 80
>>>>>>> 9691d79fdd5475284123dc58b25dbb26e7714d2e
