apiVersion: v1 
metadata: 
     name: nginx-pod
kind:  Pod
spec: 
     containers:
      - name: nginx-container 
        image: nginx
        ports:
<<<<<<< HEAD
          - containerPort: 80
=======
          - containerPort: 80
>>>>>>> e39631d2fa204f325690f2ce90ba18f06ab80257
